import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HomePage from 'components/HomePage/HomePage'
import AboutSection from 'components/AboutSection'
import SkillSection from 'components/Skill Section/SkillSection'
import ProtfolioSection from 'components/PortfolioSection/ProtfolioSection'
import Contact from 'components/Contact'
import Footer from 'components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HomePage />
        <AboutSection />
        <SkillSection />
        <ProtfolioSection />
        <Contact />
        <Footer />
      </main>
    </>
  )
}
